services:
  - type: web
    name: my-garden-helper-backend
    runtime: java
    rootDir: backend
    buildCommand: ./mvnw clean package
    startCommand: java -jar target/garden-helper-0.0.1-SNAPSHOT.jar
    plan: free